---
- name: deploy java application
  get_url:
    url: http://18.191.135.152:8081/artifactory/webapp/#/artifacts/browse/tree/General/myuat/19/target/mahaLogin-1.0.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    username: admin
    password: password
    force_basic_auth: yes
