---
- name: deploy java application
  get_url:
    url: http://52.43.65.153:8081/artifactory/vtUAT/{{deploy}}/target/mahaLogin-1.0.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    username: admin
    password: password
    force_basic_auth: yes
